### ISSUE TITLE
Default ssl_certs_path_owner: "www-data"

### ISSUE THREAD

**Issue by basnijholt** [jdauphant/ansible-role-ssl-certs#9]
When using this role in combination with your `nginx` role you might run into trouble.

in `defaults/main.yml` it says:

```
ssl_certs_path_owner: "www-data"
ssl_certs_path_group: "www-data"
```

while your `nginx` role allows for setting the user as role parameter:

```
nginx_user: "www-data"
```

My Ansible knowledge is still very limited, but could it be possible that this changes into a role parameter?

**Comment by jdauphant** [comment]
I not sure to well understand your question.

Indication that can be useful :
- This SSL role doesn't support as many system as the nginx role
- You may need something like that :

```
ssl_certs_path_owner: "{{nginx_user}}"
ssl_certs_path_group: "{{nginx_group}}"
```

**Comment by cmprescott** [comment]
If anyone else runs into this, its' pretty simple to solve at playbook level. Just have to do what's in above comment and ensure you have the nginx user & group before this role.

``` yaml
- name: CentOS 7 workaround
  hosts: centos7
  pre_tasks:

    - name: "Ensure nginx group"
      group: name="{{ nginx_group }}"

    - name: "Ensure nginx user"
      user: name="{{ nginx_user }}" group="{{ nginx_group }}"

  roles:

    - name: "Ensure self signed openssl certificate"
      role: ansible-role-ssl-certs
      ssl_certs_path_owner: "{{ nginx_user }}"
      ssl_certs_path_group: "{{ nginx_group }}"
      ssl_certs_generate_dh_param: true

    - name: "Ensure nginx reverse proxy"
      role: ansible-role-nginx
      nginx_configs:
        https:
          - ssl_certificate_key {{ ssl_certs_privkey_path }}
          - ssl_certificate     {{ ssl_certs_cert_path }}
          - ssl_dhparam         {{ ssl_certs_dhparam_path }}
.......
```
